# main.yml

# 工作流程的名字
name: Build WEB

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    branches:
      - 'main'

# 这个工作流程需要执行的任务
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    # 这个任务的步骤
    steps:
      # 拉取项目代码
      - uses: actions/checkout@v3
      # 建立 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.16.2"
      # 下载项目依赖
      - name: Flutter pub get
        run: flutter pub get
      # 打包web
      - name: build web
        run: flutter build web --web-renderer canvaskit --dart-define=FLUTTER_WEB_CANVASKIT_URL=canvaskit/
      # 配置git
      # - name: Config git
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git config --global user.name  "wyklion"
      #     git config --global user.email  "wyklion@qq.com"  
      #     git add .
      #     git commit -m "update build web"
      #     git push
      # 上传自己的FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
          server: ${{ secrets.SERVER }}
          # FTP account username
          username: ${{ secrets.USER }}
          # FTP account password
          password: ${{ secrets.PASSWORD }}
          # The local folder to copy, defaults to root project folder
          local-dir: build/web/